# Generated by Django 3.1.7 on 2021-04-07 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='bio',
            field=models.CharField(default='bobo ako', max_length=200),
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=2)),
                ('task', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletjournal.name')),
            ],
        ),
    ]
