# Generated by Django 3.1.7 on 2021-04-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0002_auto_20210408_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='profilepictures'),
        ),
        migrations.AlterField(
            model_name='name',
            name='bio',
            field=models.CharField(default='A short bio about yourself', max_length=200),
        ),
        migrations.AlterField(
            model_name='name',
            name='nickname',
            field=models.CharField(default='Your nickname', max_length=50),
        ),
    ]
