# Generated by Django 3.1.7 on 2021-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0003_auto_20210408_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='name',
            name='name',
            field=models.CharField(default='test', max_length=100, unique=True),
        ),
    ]
