# Generated by Django 3.1.7 on 2021-04-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0004_auto_20210409_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletjournal.key'),
        ),
    ]
