# Generated by Django 3.1.7 on 2021-04-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0006_today'),
    ]

    operations = [
        migrations.RenameField(
            model_name='today',
            old_name='key',
            new_name='keys',
        ),
    ]
