# Generated by Django 3.1.7 on 2021-04-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletjournal', '0007_auto_20210410_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='today',
            old_name='keys',
            new_name='key',
        ),
    ]
